version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - MONGO_USER=root
      - MONGO_PASSWORD=example
    command: npm run dev
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: